services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: experience-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./database/scripts:/scripts
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd123", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - experience-network

  webapi:
    build: 
      context: ./src/WebAPI
      dockerfile: Dockerfile
    container_name: experience-webapi
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ExperienceShareDB;User Id=sa;Password=YourStrong@Passw0rd123;TrustServerCertificate=true
    networks:
      - experience-network

volumes:
  sqldata:

networks:
  experience-network:
    driver: bridge