# docker compose for assignment 1

services:
  # database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: localfood-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyP@ssw0rd2024!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./database/scripts:/scripts:ro
    networks:
      - localfood-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "MyP@ssw0rd2024!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # api
  webapi:
    image: localfood-api:latest
    build:
      context: ./src/WebAPI
      dockerfile: Dockerfile
    container_name: localfood-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LocalFoodDB;User Id=sa;Password=MyP@ssw0rd2024!;TrustServerCertificate=true
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - localfood-network
    restart: unless-stopped

volumes:
  sqldata:
    driver: local

networks:
  localfood-network:
    driver: bridge